# Site settings
title: RecantoRecreio | lazer e diversão para família e amigos!
description: "O espaço ideal para o seu evento, lazer e diversão para família e amigos!"
baseurl: "/recantorecreio" # the subpath of your site, e.g. /blog
url: "http://recantorecreio.com.br" # the name of your domain
logo_url: img/logo.png
#logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: RecantoRecreio
    hero_description: O espaço ideal para o seu evento, lazer e diversão para família e amigos!

# Contact form
api_token: a24a1c420416706356bf1b0e55fd6200 # Enter API token here

# Contact info
contact:
    phone: (19) 99777 9078 (vivo - whatsapp)
    fixo: (19) 3887 1429
    email: recantorecreio@gmail.com
    address: Av Antônio Arten KM 2, <br> Campinas - SP, <br> (Antiga Estrada do Campo Grande)

# Horario para contato
monday_friday: 8:00 – 20:00
saturday: 10:00 – 18:00
sunday: 10:00 – 18:00

# Testimonials
#testimonials:
#    testimonials_img: parallax.jpg

# Map
map:
    zoom: 16
    address: Recanto Recreio Campinas
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com/RecantoRecreio
#twitter: http://twitter.com
#instagram: http://instagram.com
#youtube: http://youtube.com
#skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2018 RecantoRecreio - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:

theme: jekyll-theme-cayman